name: marie_app
description: "Flutter project(mock)."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.16.2 <3.0.0"
#----------------------------------BuildDependent
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  #  状態管理
  flutter_riverpod: ^2.5.1
  # チャートライブラリ
  fl_chart: ^0.67.0
  #マーキー(文字流れ再生Liv)
  marquee: ^2.2.3
  #設定UI
  settings_ui: ^2.0.2

#----------------------------------DevDependent
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  #  アイコン
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/imgs/app_icon.png"
  adaptive_icon_background: '#ff7f50'

#  追加
flutter_icons:
  android: true
  image_path: "assets/imgs/app_icon.png"

flutter:
  uses-material-design: true
  #資材path
  assets:
    - assets/imgs/
